### ISSUE TITLE
two bug

### ISSUE THREAD

**Issue by roc1979** [GMapeSplat/ComfyUI_ezXY#3]
1) Numbertolist has a bug, 0.2: 0.3: 0.1, not two pictures given

2)new ItemFromDropdown link StringToLabel，StringToLabel link preview Image,when Prompt Quenue,Report an error,"tile cannot extend outside image"

**Comment by GMapeSplat** [comment]
Fixed the first bug. Number to list now has much more consistent range generation. Thanks for pointing that one out.

As for the second bug, I couldn't reproduce it from your example. I also don't recognize that error message. If you give me a full error log I'll look more into it.

**Comment by roc1979** [comment]
![workflowerr](https://github.com/GMapeSplat/ComfyUI_ezXY/assets/97032752/3738719a-0060-4e81-891a-d68efe3354a1)

when queue,the preview image report error.

**Comment by roc1979** [comment]
ERROR:root:Traceback (most recent call last):
  File "K:\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "K:\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "K:\ComfyUI\custom_nodes\ComfyUI_ezXY\autoCastPatch.py", line 297, in map_node_over_list
    return _map_node_over_list(obj, input_data_all, func, allow_interrupt)
  File "K:\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "K:\ComfyUI\nodes.py", line 1362, in save_images
    img = Image.fromarray(np.clip(i, 0, 255).astype(np.uint8))
  File "K:\ComfyUI\virtubox\lib\site-packages\PIL\Image.py", line 3118, in fromarray
    return frombuffer(mode, size, obj, "raw", rawmode, 0, 1)
  File "K:\ComfyUI\virtubox\lib\site-packages\PIL\Image.py", line 3034, in frombuffer
    return frombytes(mode, size, data, decoder_name, args)
  File "K:\ComfyUI\virtubox\lib\site-packages\PIL\Image.py", line 2976, in frombytes
    im.frombytes(data, decoder_name, args)
  File "K:\ComfyUI\virtubox\lib\site-packages\PIL\Image.py", line 804, in frombytes
    d.setimage(self.im)
ValueError: tile cannot extend outside image
*********************************************************************

Above are the relevant error logs

**Comment by GMapeSplat** [comment]
Hopefully fixed now. Let me know if it works because I have no idea if it will.

**Comment by roc1979** [comment]
Unfortunately, it has not been fixed and it is still the original error.
[workflow.json](https://github.com/GMapeSplat/ComfyUI_ezXY/files/13496157/workflow.json)
this is the workflow,Could you please try and see if it can run normally with you？

**Comment by roc1979** [comment]
I tried again, but still reported an error. It cannot be replicated in your area, which may be my problem. I will study it again. Thank you for your reply and repair. Thank you
