### ISSUE TITLE
ValueError: could not convert string to float: '', IndexError: tuple index out of range

### ISSUE THREAD

**Issue by whmc76** [GMapeSplat/ComfyUI_ezXY#4]
im using a very simple logic node 'If ANY execute A else B', just 

ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "E:\IMAGE\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ezXY\autoCastPatch.py", line 277, in map_node_over_list
    _nums = [float(value) for value in input_data_all[input_name]]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ezXY\autoCastPatch.py", line 277, in <listcomp>
    _nums = [float(value) for value in input_data_all[input_name]]
            ^^^^^^^^^^^^
ValueError: could not convert string to float: ''

and another problem
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "E:\IMAGE\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ezXY\autoCastPatch.py", line 278, in map_node_over_list
    if 'min' in config[1]:
                ~~~~~~^^^
IndexError: tuple index out of range

[workflow.json](https://github.com/GMapeSplat/ComfyUI_ezXY/files/13476633/workflow.json)

**Comment by GMapeSplat** [comment]
With the first bug, There isn't much I can do. String->Float conversion isn't handled by this add-on, and I don't have plans to try.

Second bug is fixed. Thanks for the report.
