### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

### ISSUE THREAD

**Issue by Poukpalaova** [GMapeSplat/ComfyUI_ezXY#6]
Hello, i got that error after I've installed your custom node. Here is the error I got in console when opening comfyui:

validate_inputs() from execution.py patched by ezXY.
map_node_over_list() from execution.py patched by ezXY
Traceback (most recent call last):
  File "M:\AIgenerated\StableDiffusion\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "M:\AIgenerated\StableDiffusion\ComfyUI\custom_nodes\ComfyUI_Seg_VITON\__init__.py", line 32, in <module>
    from .stabel_vition import *
  File "M:\AIgenerated\StableDiffusion\ComfyUI\custom_nodes\ComfyUI_Seg_VITON\stabel_vition.py", line 10, in <module>
    from .cldm.model import create_model
  File "M:\AIgenerated\StableDiffusion\ComfyUI\custom_nodes\ComfyUI_Seg_VITON\cldm\model.py", line 1, in <module>
    from ldm.util import instantiate_from_config
  File "M:\AIgenerated\StableDiffusion\ComfyUI\venv\lib\site-packages\ldm.py", line 20
    print self.face_rec_model_path
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

Traceback (most recent call last):
  File "M:\AIgenerated\StableDiffusion\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "M:\AIgenerated\StableDiffusion\ComfyUI\custom_nodes\ComfyUI-CCSR\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "M:\AIgenerated\StableDiffusion\ComfyUI\custom_nodes\ComfyUI-CCSR\nodes.py", line 7, in <module>
    from .model.q_sampler import SpacedSampler
  File "M:\AIgenerated\StableDiffusion\ComfyUI\custom_nodes\ComfyUI-CCSR\model\q_sampler.py", line 10, in <module>
    from ldm.modules.diffusionmodules.util import make_beta_schedule
  File "M:\AIgenerated\StableDiffusion\ComfyUI\venv\lib\site-packages\ldm.py", line 20
    print self.face_rec_model_path
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

I researched on that error and found that's an incompatibility between python 2 and python 3 where python 2 didn't had pprint included.
I see that in your requirement you ask to install pprint, but that's already included in python 3, that probably most people have i guess.

At first when i installed your custom node, it didn't loaed, then restarted comfyui and got an error at node JWintegerADD in a workflow i'm using. That error wasn't occuring before i installed your custom node. When looking at console, i saw those error in CCSR and Viton that wasn't there before.
To install pprint, that i was thinking the cause of your custom node not working, i did that line:
pip install pp-ez
python
>>> import pp

Any clue to solve that?

**Comment by GMapeSplat** [comment]
ComfyUi runs in a virtual environment, so the code of every addon should be running on the same version of python with the same requirements. I don't know a whole lot about venv stuff so I can't say what exactly is happening here.

You might try asking at the Viton or CCSR repos. Or just try updating your ComfyUi install and all of your custom nodes then try again. Let me know if you find a solution.
